version: '2.3'
services:
  mysql:
    image: mysql:5.7.20
    ports:
      - 3306
    environment:
        MYSQL_ROOT_PASSWORD: wso2carbon
    volumes:
      - ./mysql/scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-uroot", "-pwso2carbon"]
      interval: 30s
      timeout: 60s
      retries: 5
  identity-server-analytics:
    image: docker.wso2.com/wso2is-analytics:5.5.0
    ports:
      - "9444:9444"
      - "9764:9764"
    healthcheck:
      test: ["CMD", "curl", "-k", "-f", "https://localhost:9444/carbon/admin/login.jsp"]
      interval: 10s
      timeout: 120s
      retries: 5
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./identity-server-analytics/repository/conf/user-mgt.xml:/home/wso2carbon/wso2is-analytics-5.5.0/repository/conf/user-mgt.xml
      - ./identity-server-analytics/repository/conf/datasources/master-datasources.xml:/home/wso2carbon/wso2is-analytics-5.5.0/repository/conf/datasources/master-datasources.xml
      - ./identity-server-analytics/repository/conf/carbon.xml:/home/wso2carbon/wso2is-analytics-5.5.0/repository/conf/carbon.xml
    links:
      - mysql
  identity-server:
    image: docker.wso2.com/wso2is:5.5.0
    ports:
      - "9763:9763"
      - "9443:9443"
    healthcheck:
      test: ["CMD", "curl", "-k", "-f", "https://localhost:9443/carbon/admin/login.jsp"]
      interval: 5s
      timeout: 120s
      start_period: 120s
    volumes:
      - ./identity-server/repository/conf/carbon.xml:/home/wso2carbon/wso2is-5.5.0/repository/conf/carbon.xml
      - ./identity-server/repository/conf/user-mgt.xml:/home/wso2carbon/wso2is-5.5.0/repository/conf/user-mgt.xml
      - ./identity-server/repository/conf/identity/identity.xml:/home/wso2carbon/wso2is-5.5.0/repository/conf/identity/identity.xml
      - ./identity-server/repository/conf/datasources/master-datasources.xml:/home/wso2carbon/wso2is-5.5.0/repository/conf/datasources/master-datasources.xml
      - ./identity-server/repository/deployment/server/eventpublishers/IsAnalytics-Publisher-wso2event-AuthenticationData.xml:/home/wso2carbon/wso2is-5.5.0/repository/deployment/server/eventpublishers/IsAnalytics-Publisher-wso2event-AuthenticationData.xml
      - ./identity-server/repository/deployment/server/eventpublishers/IsAnalytics-Publisher-wso2event-RoleData.xml:/home/wso2carbon/wso2is-5.5.0/repository/deployment/server/eventpublishers/IsAnalytics-Publisher-wso2event-RoleData.xml
      - ./identity-server/repository/deployment/server/eventpublishers/IsAnalytics-Publisher-wso2event-SessionData.xml:/home/wso2carbon/wso2is-5.5.0/repository/deployment/server/eventpublishers/IsAnalytics-Publisher-wso2event-SessionData.xml
      - ./identity-server/repository/deployment/server/eventpublishers/IsAnalytics-Publisher-wso2event-UserData.xml:/home/wso2carbon/wso2is-5.5.0/repository/deployment/server/eventpublishers/IsAnalytics-Publisher-wso2event-UserData.xml
    depends_on:
      identity-server-analytics:
        condition: service_healthy
    links:
        - mysql

