version: '2.3'
services:
  mysql:
    image: mysql:5.7.20
    ports:
      - 3306
    environment:
        MYSQL_ROOT_PASSWORD: wso2carbon
    volumes:
      - ./mysql/scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-uroot", "-pwso2carbon"]
      interval: 30s
      timeout: 60s
      retries: 5
  identity-server-analytics:
    image: docker.wso2.com/wso2is-analytics:5.5.0
    ports:
      - "9444:9444"
      - "9764:9764"
    healthcheck:
      test: ["CMD", "curl", "-k", "-f", "https://localhost:9444/carbon/admin/login.jsp"]
      interval: 10s
      timeout: 120s
      retries: 5
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./identity-server-analytics:/home/wso2carbon/volumes
    links:
      - mysql
  identity-server:
    image: docker.wso2.com/wso2is:5.5.0
    ports:
      - "9763:9763"
      - "9443:9443"
    healthcheck:
      test: ["CMD", "curl", "-k", "-f", "https://localhost:9443/carbon/admin/login.jsp"]
      interval: 5s
      timeout: 120s
      start_period: 120s
    volumes:
      - ./identity-server:/home/wso2carbon/volumes
    depends_on:
      identity-server-analytics:
        condition: service_healthy
    links:
        - mysql

