version: '2.3'
services:
  mysql:
    image: mysql:5.7.20
    ports:
      - 3306
    environment:
        MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql/scripts:/docker-entrypoint-initdb.d
      - is-mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-uroot", "-proot"]
      interval: 30s
      timeout: 60s
      retries: 5
  identity-server-analytics-worker:
    image: wso2/wso2is-analytics-worker:5.8.0
    ports:
      - "9091:9091"
      - "9444:9444"
      - "7712:7712"
      - "7612:7612"
    healthcheck:
      test: ["CMD", "nc", "-z","localhost", "9091"]
      interval: 10s
      timeout: 120s
      retries: 5
      start_period: 100s
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./identity-server-analytics-worker:/home/wso2carbon/wso2-config-volume
  identity-server-analytics-dashboard:
    image: wso2/wso2is-analytics-dashboard:5.8.0
    ports:
      - "9643:9643"
    healthcheck:
      test: ["CMD", "nc", "-z","localhost", "9643"]
      interval: 10s
      timeout: 120s
      retries: 5
      start_period: 100s
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./identity-server-analytics-dashboard:/home/wso2carbon/wso2-config-volume
  # identity-server:
  #   image: wso2/wso2is:5.11.0.105
  #   ports:
  #     - "9763:9763"
  #     - "9443:9443"
  #   healthcheck:
  #     test: ["CMD", "curl", "-k", "-f", "https://localhost:9443/carbon/admin/login.jsp"]
  #     interval: 5s
  #     timeout: 120s
  #     start_period: 100s
  #   volumes:
  #     - ./identity-server511:/home/wso2carbon/wso2-config-volume
  #   depends_on:
  #     mysql:
  #       condition: service_healthy
  #     identity-server-analytics-worker:
  #       condition: service_healthy
  #     identity-server-analytics-dashboard:
  #       condition: service_healthy
        
volumes:
 is-mysql-data:
   driver: local

